# Generated by Django 6.1 on 2026-09-11 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schematics', '0003_harden_constraints_and_protected_storage'),
        ('subscriptions', '0003_harden_constraints_and_protected_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('schematic', 'خرید تکی شماتیک'), ('subscription', 'خرید اشتراک')], max_length=20, verbose_name='نوع خرید')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('authority', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='کد Authority')),
                ('gateway', models.CharField(default='mock', max_length=32, verbose_name='درگاه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('ref_id', models.CharField(blank=True, max_length=64, verbose_name='کد پیگیری درگاه')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='subscriptions.plan', verbose_name='پلن اشتراک')),
                ('schematic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='schematics.schematic', verbose_name='شماتیک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_pay_user_status')],
            },
        ),
    ]
