# Generated by Django 6.1 on 2026-09-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='claim_token_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان صدور نشست مهمان'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='guest_account_created',
            field=models.BooleanField(default=False),
        ),
    ]
