# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_guest_claim_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='schematic_ids',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Snapshot of schematic pks charged in this checkout (batch or single).',
                verbose_name='شناسه شماتیک‌های سبد',
            ),
        ),
    ]
