# Generated by Django 6.1 on 2026-09-12 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_harden_constraints_and_protected_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('otp_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password reset challenge',
                'verbose_name_plural': 'Password reset challenges',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone_number', 'used_at', 'expires_at'], name='accounts_pa_phone_n_84d535_idx')],
            },
        ),
    ]
