# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_password_reset_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name='Wallet balance (Tomans)',
            ),
        ),
    ]
