# Generated by Django 6.1 on 2026-09-02 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price'], 'verbose_name': 'پلن اشتراک', 'verbose_name_plural': 'پلن\u200cهای اشتراک'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'اشتراک کاربر', 'verbose_name_plural': 'اشتراک\u200cهای کاربران'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='مدت اعتبار (روز)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان پلن'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='subscriptions.plan', verbose_name='پلن'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی\u200cشده'), ('canceled', 'لغو شده')], db_index=True, default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status', 'end_date'], name='subscriptio_user_id_a0684e_idx'),
        ),
    ]
