# Generated by Django 6.1 on 2026-09-11 21:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_plan_options_alter_usersubscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='idx_sub_user_status_end',
            old_name='subscriptio_user_id_a0684e_idx',
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان پلن'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='plan_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='subscription_end_after_start'),
        ),
    ]
