# Generated by Django 6.1 on 2026-08-22 19:58

import django.db.models.deletion
import schematics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchematicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Schematic Category',
                'verbose_name_plural': 'Schematic Categories',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, max_length=170)),
                ('technical_code', models.CharField(blank=True, help_text='Board or technical model code (e.g., SM-S918B, A2638)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_models', to='schematics.brand')),
            ],
            options={
                'verbose_name': 'Phone Model',
                'verbose_name_plural': 'Phone Models',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed notes, repair technician tips, or troubleshooting guides.')),
                ('is_free', models.BooleanField(default=False, help_text='If checked, any registered user can download without payment.')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='Price for single purchase in Tomans (0 if free or subscription-only).', max_digits=10)),
                ('requires_subscription', models.BooleanField(default=True, help_text='Whether this schematic is included in active subscription plans.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematics', to='schematics.phonemodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schematics', to='schematics.schematiccategory')),
            ],
            options={
                'verbose_name': 'Schematic',
                'verbose_name_plural': 'Schematics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchematicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=schematics.models.schematic_file_upload_path)),
                ('file_title', models.CharField(help_text='e.g., Main Motherboard PDF, Sub-board Layout', max_length=150)),
                ('file_size_bytes', models.BigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='schematics.schematic')),
            ],
            options={
                'verbose_name': 'Schematic File',
                'verbose_name_plural': 'Schematic Files',
            },
        ),
    ]
