# Generated by Django 6.1 on 2026-09-02 11:45

import django.db.models.deletion
import schematics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchematicPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پرداخت\u200cشده (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
            ],
            options={
                'verbose_name': 'خرید تکی شماتیک',
                'verbose_name_plural': 'خریدهای تکی شماتیک',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'ordering': ['brand', 'name'], 'verbose_name': 'مدل گوشی', 'verbose_name_plural': 'مدل\u200cهای گوشی'},
        ),
        migrations.AlterModelOptions(
            name='schematic',
            options={'ordering': ['-created_at'], 'verbose_name': 'شماتیک', 'verbose_name_plural': 'شماتیک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='schematiccategory',
            options={'verbose_name': 'دسته\u200cبندی نقشه', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای نقشه'},
        ),
        migrations.AlterModelOptions(
            name='schematicfile',
            options={'verbose_name': 'فایل شماتیک', 'verbose_name_plural': 'فایل\u200cهای شماتیک'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_models', to='schematics.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام مدل'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=170, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='technical_code',
            field=models.CharField(blank=True, db_index=True, help_text='مانند SM-S918B, A2638', max_length=100, verbose_name='کد فنی / شناسه برد'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schematics', to='schematics.schematiccategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تخصصی عیب\u200cیابی و مسیرهای ولتاژ', verbose_name='نکات فنی و راه\u200cحل\u200cها'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='is_free',
            field=models.BooleanField(db_index=True, default=False, help_text='در صورت فعال بودن، برای تمام کاربران بدون اشتراک قابل دانلود است.', verbose_name='رایگان'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='phone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematics', to='schematics.phonemodel', verbose_name='مدل گوشی'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت خرید تکی (تومان)'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='requires_subscription',
            field=models.BooleanField(db_index=True, default=True, help_text='آیا با اشتراک فعال قابل مشاهده است؟', verbose_name='نیاز به اشتراک'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان شماتیک'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='schematiccategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='schematiccategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='schematiccategory',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='schematicfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود'),
        ),
        migrations.AlterField(
            model_name='schematicfile',
            name='file',
            field=models.FileField(upload_to=schematics.models.schematic_file_upload_path, verbose_name='فایل نقشه / بردویو'),
        ),
        migrations.AlterField(
            model_name='schematicfile',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='حجم فایل (بایت)'),
        ),
        migrations.AlterField(
            model_name='schematicfile',
            name='file_title',
            field=models.CharField(max_length=150, verbose_name='عنوان فایل'),
        ),
        migrations.AlterField(
            model_name='schematicfile',
            name='schematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='schematics.schematic', verbose_name='شماتیک مربوطه'),
        ),
        migrations.AddIndex(
            model_name='phonemodel',
            index=models.Index(fields=['brand', 'name'], name='schematics__brand_i_917e68_idx'),
        ),
        migrations.AddIndex(
            model_name='schematic',
            index=models.Index(fields=['phone_model', 'category'], name='schematics__phone_m_85acca_idx'),
        ),
        migrations.AddIndex(
            model_name='schematic',
            index=models.Index(fields=['is_free', 'requires_subscription'], name='schematics__is_free_05c0f5_idx'),
        ),
        migrations.AddField(
            model_name='schematicpurchase',
            name='schematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='schematics.schematic', verbose_name='شماتیک خریداری\u200cشده'),
        ),
        migrations.AddField(
            model_name='schematicpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematic_purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='schematicpurchase',
            index=models.Index(fields=['user', 'schematic'], name='schematics__user_id_99c357_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schematicpurchase',
            unique_together={('user', 'schematic')},
        ),
    ]
