# Generated by Django 6.1 on 2026-09-11 21:16

import django.core.validators
import schematics.models
import schematics.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0002_schematicpurchase_alter_brand_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schematiccategory',
            options={'ordering': ['title'], 'verbose_name': 'دسته\u200cبندی نقشه', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای نقشه'},
        ),
        migrations.AlterModelOptions(
            name='schematicfile',
            options={'ordering': ['id'], 'verbose_name': 'فایل شماتیک', 'verbose_name_plural': 'فایل\u200cهای شماتیک'},
        ),
        migrations.AlterModelOptions(
            name='schematicpurchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'خرید تکی شماتیک', 'verbose_name_plural': 'خریدهای تکی شماتیک'},
        ),
        migrations.RemoveIndex(
            model_name='phonemodel',
            name='schematics__brand_i_917e68_idx',
        ),
        migrations.RemoveIndex(
            model_name='schematicpurchase',
            name='schematics__user_id_99c357_idx',
        ),
        migrations.RenameIndex(
            model_name='schematic',
            new_name='idx_schematic_model_cat',
            old_name='schematics__phone_m_85acca_idx',
        ),
        migrations.RenameIndex(
            model_name='schematic',
            new_name='idx_schematic_access_flags',
            old_name='schematics__is_free_05c0f5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='phonemodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schematicpurchase',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='is_free',
            field=models.BooleanField(db_index=True, default=False, help_text='در صورت فعال بودن، برای تمام کاربران احراز هویت\u200cشده بدون اشتراک قابل دانلود است.', verbose_name='رایگان'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید تکی (تومان)'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='requires_subscription',
            field=models.BooleanField(db_index=True, default=True, help_text='آیا با اشتراک فعال قابل دانلود است؟', verbose_name='نیاز به اشتراک'),
        ),
        migrations.AlterField(
            model_name='schematicfile',
            name='file',
            field=models.FileField(storage=schematics.storage.ProtectedSchematicStorage(), upload_to=schematics.models.schematic_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'zip'])], verbose_name='فایل نقشه / بردویو'),
        ),
        migrations.AlterField(
            model_name='schematicpurchase',
            name='price_paid',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداخت\u200cشده (تومان)'),
        ),
        migrations.AddIndex(
            model_name='schematic',
            index=models.Index(fields=['-created_at'], name='idx_schematic_created_desc'),
        ),
        migrations.AddIndex(
            model_name='schematicfile',
            index=models.Index(fields=['schematic', '-created_at'], name='idx_schematicfile_parent'),
        ),
        migrations.AddConstraint(
            model_name='phonemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'slug'), name='uniq_phonemodel_brand_slug'),
        ),
        migrations.AddConstraint(
            model_name='phonemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='uniq_phonemodel_brand_name'),
        ),
        migrations.AddConstraint(
            model_name='schematic',
            constraint=models.UniqueConstraint(fields=('phone_model', 'category', 'title'), name='uniq_schematic_model_category_title'),
        ),
        migrations.AddConstraint(
            model_name='schematic',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='schematic_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='schematicpurchase',
            constraint=models.UniqueConstraint(fields=('user', 'schematic'), name='uniq_schematic_purchase_user_schematic'),
        ),
        migrations.AddConstraint(
            model_name='schematicpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('price_paid__gte', 0)), name='schematic_purchase_price_non_negative'),
        ),
    ]
